name: attributes
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:   
    - opencv-python==4.1.2.30
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pandas
    - scipy
    - tqdm
    - seaborn
    - scikit-learn
    - tensorboard
    - tensorboardX